name: Check Steam Workshop IDs

on:
  push:
    paths:
      - 'cs2/**/counterstrikesharp/configs/plugins/MapChooser/maps.txt'  # 当任何 maps.txt 文件发生变化时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  check-workshop-ids:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码库
      uses: actions/checkout@v3
      with:
        ref: master  # 确保检出的是主分支

    - name: 删除现有的 disable-unavailable-ids 分支
      run: |
        git branch -D disable-unavailable-ids || true
        git push origin --delete disable-unavailable-ids || true

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 查找并保存所有 maps.txt 文件路径
      id: find_maps
      run: |
        find cs2 -path "*/counterstrikesharp/configs/plugins/MapChooser/maps.txt" > map_files.txt

    - name: 运行检查脚本
      id: check_script
      run: |
        touch unavailable_ids.txt
        while IFS= read -r map_file; do
          python scripts/check_workshop_ids.py "$map_file" || echo "$map_file" >> failed_maps.txt
        done < map_files.txt
      continue-on-error: true

    - name: 读取不可用的 IDs
      id: read_unavailable_ids
      run: |
        if [ -f unavailable_ids.txt ]; then
          ids=$(cat unavailable_ids.txt)
          echo "unavailable_ids=$ids" >> $GITHUB_ENV
        fi
        if [ -f failed_maps.txt ]; then
          failed_maps=$(cat failed_maps.txt)
          echo "failed_maps=$failed_maps" >> $GITHUB_ENV
        fi

    - name: 输出结果
      run: |
        if [ -s unavailable_ids.txt ]; then
          echo -e "\033[91m部分 Steam Workshop IDs 不可用。\033[0m"
        else
          echo -e "\033[92m所有 Steam Workshop IDs 均可用。\033[0m"
        fi

    - name: 创建拉取请求
      if: steps.read_unavailable_ids.outputs.unavailable_ids  # 仅在存在不可用 ID 时触发
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: '禁用不可用的 Steam Workshop IDs'
        title: '[自动]禁用不可用的 Steam Workshop IDs'
        body: |
          部分 Steam Workshop IDs 经系统检测当前不可用。已将其对应的 enabled 字段从 1 改为 0。

          不可用 ID 列表:
          ${{ env.unavailable_ids }}

          受影响的 maps.txt 文件:
          ${{ env.failed_maps }}
          
          可能是临时性的调整,请审核,并确认更改。
        branch: 'disable-unavailable-ids'
        base: master